### PR TITLE
Remove OpenMPSupport flag from DirectXTex

### PR DESCRIPTION
**Pull request by rickbrew**
PDN 4.2.2 removed the OpenMP DLLs because they were no longer necessary.

However, it looks like DirectXTex is still loading the DLL because it's compiled with the `OpenMPSupport` flag. However, it's _not_ compiled with the `_OPENMP` preprocessor definition, so it's not actually _using_ OpenMP.

I think this problem is being caused by not being able to load VCOMP140.DLL: https://forums.getpaint.net/topic/115151-updated-version-not-opening-picture-file/?tab=comments#comment-563056 . I used Process Explorer to verify that VCOMP140.DLL is loaded when using the DDSFileTypePlus plugin. It gets pulled from C:\windows\system32 on my system.

If this is the case then I'll need to release an updated Paint.NET 4.2.3 with a fixed DDSFileTypePlus plugin.

### CODE REVIEW

**Comment by rickbrew** [comment]
There's only 1 real commit -- the rest should be squashed

**Comment by rickbrew** [comment]
However, if OpenMP support would be beneficial for performance, I can instead re-add VCOMP140.DLL to the Paint.NET installation. DDSFileTypePlus would still need to be modified to add the _OPENMP preprocessor definition.

It's only used by `CompressBC_Parallel` in DirectXTexCompres.cpp

**Comment by 0xC0000054** [comment]
>DDSFileTypePlus would still need to be modified to add the _OPENMP preprocessor definition.

@rickbrew 

_OPENMP is automatically defined by the compiler, see https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019#microsoft-specific-predefined-macros

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rickbrew** [comment]
Hmm, strange, because the block of code within `#ifdef _OPENMP` was marked as inactive in the IDE _Edit: or at least I thought it was, now it's showing as active (not greyed out)_

I'll push out a 4.2.3 update that re-includes `vcomp140.dll`

**Pull request closed without merging**
